- name: Check if ping is available
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Check ping path
      ansible.builtin.command: "which ping"
      register: ping_path
      changed_when: false
      ignore_errors: yes

    - name: Display ping location
      ansible.builtin.debug:
        msg: "Ping is installed at {{ ping_path.stdout }}"
