- name: Check if the target is reachable without using ping
  hosts: localhost
  tasks:
    - name: Wait for the target to respond (port 80 as example)
      ansible.builtin.wait_for:
        host: "64.233.180.138"
        port: 80
        timeout: 10
      register: reachability_result
      ignore_errors: true

    - name: Show the result
      ansible.builtin.debug:
        msg: "Target is {{ 'reachable' if reachability_result.state == 'started' else 'not reachable' }}"


