---
- name: Monitor network and log incidents in ServiceNow
  hosts: localhost
  gather_facts: true
  vars:
    targets:
      - "64.233.180.138"
      - "192.0.43.10"
    service_now:
      instance: "dev262979.service-now.com"
      username: "elt_agent"
      password: "o@.CSQwgo^z6W!s6"
      table: "incident"
      impact: "3"
      urgency: "3"
      short_description: "Packet loss detected"

  tasks:
    - name: Check if device is reachable (wait_for)
      ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 22  # SSH port (can change to 80 for HTTP or other relevant ports)
        timeout: 5
      register: reachability_results
      ignore_errors: true
      loop: "{{ targets }}"

    - name: Print reachability results
      ansible.builtin.debug:
        msg: "Device {{ item.item }} is {{ 'reachable' if item.state == 'started' else 'not reachable' }}"
      loop: "{{ reachability_results.results }}"

    # - name: Run traceroute if device is unreachable
    #   community.general.traceroute:
    #     host: "{{ item.item }}"
    #   register: traceroute_result
    #   loop: "{{ reachability_results.results }}"
    #   when: item.state != "started"
    #   ignore_errors: yes

    # - name: Print traceroute output
    #   ansible.builtin.debug:
    #     msg: "{{ traceroute_result.results | map(attribute='stdout') | list }}"
    #   when: traceroute_result is defined

    - name: Log incident in ServiceNow if device is unreachable
      ansible.builtin.uri:
        url: "https://{{ service_now.instance }}/api/now/table/{{ service_now.table }}"
        method: POST
        user: "{{ service_now.username }}"
        password: "{{ service_now.password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          impact: "{{ service_now.impact }}"
          urgency: "{{ service_now.urgency }}"
          short_description: "{{ service_now.short_description }}"
          description: "Device {{ item.item }} is not reachable at {{ ansible_date_time.iso8601 }}"
        status_code: 201
      when: item.state != "started"
      loop: "{{ reachability_results.results }}"
      ignore_errors: yes
