- name: Check if specific devices are reachable using Ansible ping module
  hosts: 64.233.180.138, 192.0.43.10  # Replace with your target IPs
  gather_facts: no
  tasks:
    - name: Ping specific devices
      ansible.builtin.ping:
