- name: Install iputils on macOS using Homebrew
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Ensure Homebrew is installed
      ansible.builtin.command: "/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
      args:
        creates: /usr/local/bin/brew
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install iputils using Homebrew
      community.general.homebrew:
        name: iputils
        state: present
      when: ansible_facts['os_family'] == "Darwin"

