---
- name: incident creator
  hosts: localhost
  gather_facts: yes
 
  vars:
    instance: "dev247928.service-now.com"
    username: "admin"
    password: "%ml4Vs9RXE/s"
    incident_table: "incident"
 
 
  tasks:
    
    - name: Create incident 
      ansible.builtin.uri:
        url: "https://{{ instance }}/api/now/table/{{ incident_table }}"
        method: POST
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          short_description: "(Incident Created)"
          description: "sample incident"
          impact: "2"
          urgency: "2"
        status_code: [200, 201]
      
 
