---
- name: ServiceNow Ticket Updater
  hosts: localhost
  gather_facts: no

  vars:
    instance: "dev247928.service-now.com"
    username: "admin"
    password: "%ml4Vs9RXE/s"
    incident_table: "incident"
    request_table: "sc_request"

    # Ticket details for update
    ticket_type: ""   
    sys_id: ""  
    short_description: ""
    description: ""
    impact: "2"     
    urgency: "2"    
    state: ""  

  tasks:
    - name: Set table name based on ticket type
      set_fact:
        table_name: "{{ incident_table if ticket_type == 'incident' else request_table }}"

    - name: Prepare request body for update
      set_fact:
        request_body: >-
          {%- if ticket_type == 'incident' -%}
          {
            "short_description": "{{ short_description }}",
            "description": "{{ description }}",
            "impact": "{{ impact }}",
            "urgency": "{{ urgency }}",
            "state": "{{ state }}"
          }
          {%- else -%}
          {
            "short_description": "{{ short_description }}",
            "description": "{{ description }}",
            "state": "{{ state }}"
          }
          {%- endif -%}

    - name: Update Ticket in ServiceNow
      ansible.builtin.uri:
        url: "https://{{ instance }}/api/now/table/{{ table_name }}/{{ sys_id }}"
        method: PATCH
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body: "{{ request_body | from_yaml }}"
        status_code: [200, 204]
      register: response

    - name: Show Updated Ticket Details
      debug:
        msg: "{{ response.json }}"
