---
- name: Create ServiceNow Incident or Request
  hosts: localhost
  gather_facts: no

  vars:
    instance: "dev247928.service-now.com"
    username: "admin"
    password: "%ml4Vs9RXE/s"
    
    # User inputs
    ticket_type: "incident"  # Change to "request" for creating a request
    short_description: "New Ticket Created"
    description: "This is a new service request or incident."
    priority: "3"
    impact: "2"
    urgency: "2"
    assigned_to: "admin"
    assignment_group: "IT Support"
    comments: "This is a new ticket."
    work_notes: "Initial notes added."
    due_date: "2025-03-20"
    request_state: "requested"
    stage: "requested"
    approval: "not requested"
    category: "hardware"
    service_offering: "IT Helpdesk"
    contact_type: "phone"

  tasks:
    - name: Determine table based on ticket_type
      set_fact:
        table_name: "{{ 'incident' if ticket_type == 'incident' else 'sc_request' }}"

    - name: Prepare request body for creation
      set_fact:
        request_body: >
          {
            "short_description": "{{ short_description }}",
            "description": "{{ description }}",
            "priority": "{{ priority }}",
            "impact": "{{ impact }}",
            "urgency": "{{ urgency }}",
            "assigned_to": "{{ assigned_to }}",
            "assignment_group": "{{ assignment_group }}",
            "comments": "{{ comments }}",
            "work_notes": "{{ work_notes }}",
            "due_date": "{{ due_date }}",
            "request_state": "{{ request_state }}",
            "stage": "{{ stage }}",
            "approval": "{{ approval }}",
            "category": "{{ category }}",
            "service_offering": "{{ service_offering }}",
            "contact_type": "{{ contact_type }}"
          }

    - name: Create Incident or Request in ServiceNow
      ansible.builtin.uri:
        url: "https://{{ instance }}/api/now/table/{{ table_name }}?sysparm_suppress_auto_sys_field=true"
        method: POST
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body: "{{ request_body }}"
        status_code: [200, 201]
      register: response

    - name: Show Created Ticket Details
      debug:
        msg: "{{ response.json }}"
