---
- name: incident updater
  hosts: localhost
  gather_facts: yes
 
  vars:
    sys_id2: ""
    instance: "dev247928.service-now.com"
    username: "admin"
    password: "%ml4Vs9RXE/s"
    incident_table: "incident"
      
 
 
  tasks:
    
    - name: update incident
      ansible.builtin.uri:
        url: "https://{{ instance }}/api/now/table/{{ incident_table }}/{{ sys_id2 }}"
        method: PATCH
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          state: "resolved"
          short_description: "Incident update"
          description: "incident updated description"
        status_code: [200, 201]
      
 
