---
- name: Update ServiceNow Incident or Request
  hosts: localhost
  gather_facts: no

  vars:
    instance: "dev247928.service-now.com"
    username: "admin"
    password: "%ml4Vs9RXE/s"

    # User inputs
    ticket_type: "incident"  # Change to "request" for updating a request
    sys_id: "107d22668310a210d081f696feaad302"  # Provide the existing ticket sys_id
    short_description: "Updated Ticket Description"
    description: "Updated ticket details."
    priority: "3"
    impact: "2"
    urgency: "2"
    state: "2"  # 1 = New, 2 = In Progress, etc.
    assigned_to: "admin"
    assignment_group: "IT Support"
    comments: "Ticket is being worked on."
    work_notes: "Engineer started troubleshooting."
    due_date: "2025-03-20"
    escalation: "1"
    request_state: "approved"
    stage: "fulfilling"
    approval: "approved"
    category: "network"
    service_offering: "IT Helpdesk"
    contact_type: "email"

  tasks:
    - name: Determine table based on ticket_type
      set_fact:
        table_name: "{{ 'incident' if ticket_type == 'incident' else 'sc_request' }}"

    - name: Prepare request body for update
      set_fact:
        request_body: >-
          {%- if ticket_type == 'incident' -%}
          {
            "short_description": "{{ short_description }}",
            "description": "{{ description }}",
            "impact": "{{ impact }}",
            "urgency": "{{ urgency }}",
            "priority": "{{ priority }}",
            "comments": "{{ comments }}",
            "work_notes": "{{ work_notes }}"
            "state": "{{ state }}"
          }
          {%- else -%}
          {
            "short_description": "{{ short_description }}",
            "description": "{{ description }}",
            "priority": "{{ priority }}",
            "assigned_to": "{{ assigned_to }}",
            "assignment_group": "{{ assignment_group }}",
            "comments": "{{ comments }}",
            "work_notes": "{{ work_notes }}",
            "request_state": "{{ request_state }}",
            "stage": "{{ stage }}",
            "approval": "{{ approval }}",
            "category": "{{ category }}",
            "service_offering": "{{ service_offering }}",
            "contact_type": "{{ contact_type }}"
          }
          {%- endif -%}
    - name: Update Incident or Request in ServiceNow
      ansible.builtin.uri:
        url: "https://{{ instance }}/api/now/table/{{ table_name }}/{{ sys_id }}"
        method: PATCH
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body: "{{ request_body }}"
        status_code: [200, 204]
      register: response

    - name: Show Updated Ticket Details
      debug:
        msg: "{{ response.json }}"
