---
- name: incident creator
  hosts: localhost
  gather_facts: yes
 
  vars:
    sys_id2: ""
    service_now:
      instance: "dev247928.service-now.com"
      username: "admin"
      password: "%ml4Vs9RXE/s"
      incident_table: "incident"
 
 
  tasks:
    
    - name: Create incident 
      ansible.builtin.uri:
        url: "https://{{ service_now.instance }}/api/now/table/{{ service_now.incident_table }}"
        method: POST
        user: "{{ service_now.username }}"
        password: "{{ service_now.password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          short_description: "(Incident Created)"
          description: "sample incident"
          impact: "2"
          urgency: "2"
        status_code: [200, 201]
      
 
